version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - /volume1/docker/genshin-upgrader/frontend/genshin-upgrader-frontend:/usr/share/nginx/html
      - /volume1/docker/genshin-upgrader/frontend/site.conf:/etc/nginx/conf.d/default.conf
      - /usr/local/share/acme.sh/*.pillars.ch:/etc/nginx/certs
    networks:
      - default
    ports:
      - "5116:80"
      - "5117:443"
    environment:
      - SUPPORT_EMAIL=simongloor@pillars.ch
    depends_on:
      - php
  php:
    image: php:7-fpm
    volumes:
      - /volume1/docker/genshin-upgrader/frontend/genshin-upgrader-frontend:/usr/share/nginx/html
    networks:
      - default

networks:
  default:
    driver: bridge
